[theme]
primaryColor = "#0f2338"
backgroundColor = "#f8fafd"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
